version: '3'

services:
  cubicle:
    build: .
    image: brainpower/cubicle:code-1.939-share-1.0.125
    ports:
      - '8443:8443'
    command: code-server --allow-http --no-auth
    working_dir: '/repo'
    volumes:
      - '.:/repo'
